DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS asset_number VARCHAR(100); EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS unit_prefix VARCHAR(100); EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS unit_name VARCHAR(255); EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS unit_address TEXT; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS environment VARCHAR(255); EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS distance DECIMAL(10, 2); EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS criticality VARCHAR(100); EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS incident BOOLEAN DEFAULT false; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS requester_name VARCHAR(255); EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS requester_registration VARCHAR(100); EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS requester_phone VARCHAR(50); EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS travel_cost DECIMAL(12, 2) DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS labor_cost DECIMAL(12, 2) DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS material_cost DECIMAL(12, 2) DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS total_cost DECIMAL(12, 2) DEFAULT 0; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS observations TEXT; EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS signature_contracted VARCHAR(1024); EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS signature_dependency VARCHAR(1024); EXCEPTION WHEN duplicate_column THEN null; END $$;
DO $$ BEGIN ALTER TABLE public.service_orders ADD COLUMN IF NOT EXISTS items JSONB DEFAULT '[]'::jsonb; EXCEPTION WHEN duplicate_column THEN null; END $$;
